Repository DanielDucuara2018/hispanie_backend, pull requests merged in 2025-03, with the labels that each got.

#11 :bug: Fix social networks
  hispanie/action/business.py
  hispanie/schema/business.py
  hispanie/schema/event.py
  hispanie/schema/social_network.py
Labels: bug, enhancement

#12 ❇️ Added activities endpoints
  .pre-commit-config.yaml
  hispanie/action/__init__.py
  hispanie/action/activity.py
  hispanie/action/business.py
  hispanie/action/event.py
  hispanie/api/api.py
  hispanie/api/routers/activity.py
  hispanie/api/routers/tag.py
  hispanie/errors.py
  hispanie/model/__init__.py
  hispanie/model/account.py
  hispanie/model/activity.py
  hispanie/model/business.py
  hispanie/model/event.py
  hispanie/model/file.py
  hispanie/model/social_network.py
  hispanie/model/tag.py
  hispanie/schema/__init__.py
  hispanie/schema/activity.py
  hispanie/schema/event.py
  hispanie/utils.py
  pyproject.toml
Labels: enhancement

#13 :sparkles: Change relationship to zero to many with files
  hispanie/action/business.py
  hispanie/action/event.py
  hispanie/api/routers/business.py
  hispanie/model/__init__.py
  hispanie/model/business.py
  hispanie/model/business_file.py
  hispanie/model/event.py
  hispanie/model/event_file.py
  hispanie/model/file.py
  hispanie/schema/account.py
Labels: bug, enhancement

#14 :sparkles: Handle event and business update
  hispanie/action/account.py
  hispanie/action/business.py
  hispanie/action/event.py
  hispanie/model/__init__.py
  hispanie/schema/account.py
  hispanie/schema/activity.py
  hispanie/schema/business.py
  hispanie/schema/event.py
  hispanie/schema/file.py
  hispanie/schema/social_network.py
  hispanie/utils.py
Labels: enhancement

#15 Fixed some idempotency cases and added rollback for db errors
  .gitignore
  hispanie/action/activity.py
  hispanie/action/event.py
  hispanie/action/tag.py
  hispanie/db.py
  hispanie/errors.py
  hispanie/model/activity.py
  hispanie/model/base.py
  hispanie/schema/activity.py
  hispanie/schema/event.py
  hispanie/utils.py
Labels: enhancement

#18 :sparkles: Add periodicity to events
  hispanie/api/api.py
  hispanie/model/__init__.py
  hispanie/model/event.py
  hispanie/schema/event.py
  setup.py
Labels: enhancement

#17 🟢 Added tickets endpoints
  hispanie/action/__init__.py
  hispanie/action/account.py
  hispanie/action/business.py
  hispanie/action/event.py
  hispanie/action/file.py
  hispanie/action/ticket.py
  hispanie/api/api.py
  hispanie/api/routers/activity.py
  hispanie/api/routers/ticket.py
  hispanie/errors.py
  hispanie/model/__init__.py
  hispanie/model/base.py
  hispanie/model/event.py
  hispanie/model/ticket.py
  hispanie/schema/__init__.py
  hispanie/schema/activity.py
  hispanie/schema/event.py
  hispanie/schema/ticket.py
Labels: enhancement

#19 Fixed alembic revision process
  alembic/README.md
  alembic/alembic.ini
  alembic/env.py
  alembic/script.py.mako
  alembic/versions/c5614ae0da1b_0001_initial_revision.py
  hispanie/action/account.py
  hispanie/action/activity.py
  hispanie/action/business.py
  hispanie/action/event.py
  hispanie/action/file.py
  hispanie/action/tag.py
  hispanie/action/ticket.py
  hispanie/api/api.py
  hispanie/config.py
  hispanie/db.py
  hispanie/model/base.py
Labels: enhancement

#20 :sparkles: Increase description length
  hispanie/schema/business.py
  hispanie/schema/event.py
Labels: enhancement

#21 :bug: Fix periodic task for events and return all events and business
  hispanie/api/api.py
  hispanie/api/routers/business.py
  hispanie/api/routers/event.py
Labels: bug
